export const tempdata=[
    {
        "id":1,
        "first_name":"Reinald",
        "last_name":"Fumagallo",
        "email":"rfumagallo0@miitbeian.gov.cn",
        "date_of_birth":"1992-10-23T12:28:27Z",
        "age":24,
        "country":"Nigeria",
        "phone":"702-247-4740"
    },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // },
    // {
    //     id:1,
    //     first_name:"Reinald",
    //     last_name:"Fumagallo",
    //     email:"rfumagallo0@miitbeian.gov.cn",
    //     date_of_birth:"1992-10-23T12:28:27Z",
    //     age:24,
    //     country:"Nigeria",
    //     phone:"702-247-4740"
    // }
]